// <auto-generated />
using System;
using ConsultorioAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultorioAPI.data.migrations
{
    [DbContext(typeof(consultorioDBContext))]
    [Migration("20230715221617_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsultorioAPI.Model.Convecciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conveccion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Convecciones");
                });

            modelBuilder.Entity("ConsultorioAPI.Model.EstadoCivil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CivilNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadoCivil");
                });

            modelBuilder.Entity("OdontologiaWeb.Models.Anamnesis", b =>
                {
                    b.Property<string>("Id_Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Emf_Actual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo_Consulta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Anamnesis");
                });

            modelBuilder.Entity("OdontologiaWeb.Models.Ant_Familiar", b =>
                {
                    b.Property<string>("Id_Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Alt_Coagulatorias")
                        .HasColumnType("int");

                    b.Property<int>("Cancer")
                        .HasColumnType("int");

                    b.Property<int>("Cardiopatias")
                        .HasColumnType("int");

                    b.Property<int>("Ceda_Dental")
                        .HasColumnType("int");

                    b.Property<int>("Diabetes")
                        .HasColumnType("int");

                    b.Property<int>("Embarazo")
                        .HasColumnType("int");

                    b.Property<int>("Enf_Respiratoria")
                        .HasColumnType("int");

                    b.Property<int>("Fieb_Reumatica")
                        .HasColumnType("int");

                    b.Property<int>("Fre_Cepillado")
                        .HasColumnType("int");

                    b.Property<int>("Hepatitis")
                        .HasColumnType("int");

                    b.Property<int>("Hipertension")
                        .HasColumnType("int");

                    b.Property<int>("Infecciones")
                        .HasColumnType("int");

                    b.Property<int>("Lactancia")
                        .HasColumnType("int");

                    b.Property<int>("Meses")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Organos_Sentidos")
                        .HasColumnType("int");

                    b.Property<string>("Otros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sinusitis")
                        .HasColumnType("int");

                    b.Property<int>("Ten_Arterial")
                        .HasColumnType("int");

                    b.Property<int>("Trans_Gastricos")
                        .HasColumnType("int");

                    b.Property<int>("Trans_Neumologico")
                        .HasColumnType("int");

                    b.Property<int>("Trata_Medico")
                        .HasColumnType("int");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Ant_Familiar");
                });

            modelBuilder.Entity("OdontologiaWeb.Models.Ciudad", b =>
                {
                    b.Property<int>("Id_Ciudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Ciudad"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("Id_Departamento")
                        .HasColumnType("int");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Ciudad");

                    b.ToTable("Ciudad");
                });

            modelBuilder.Entity("OdontologiaWeb.Models.Departamento", b =>
                {
                    b.Property<int>("Id_Departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Departamento"));

                    b.Property<string>("NombreDepartamento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Departamento");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("OdontologiaWeb.Models.Estomatologico", b =>
                {
                    b.Property<int>("Carrillos")
                        .HasColumnType("int");

                    b.Property<int>("Encias")
                        .HasColumnType("int");

                    b.Property<int>("Frenillos")
                        .HasColumnType("int");

                    b.Property<int>("Glan_Salivales")
                        .HasColumnType("int");

                    b.Property<string>("Id_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Labios")
                        .HasColumnType("int");

                    b.Property<int>("Lengua")
                        .HasColumnType("int");

                    b.Property<int>("Maxilares")
                        .HasColumnType("int");

                    b.Property<int>("Musculos")
                        .HasColumnType("int");

                    b.Property<int>("Orofarige")
                        .HasColumnType("int");

                    b.Property<int>("Paladar")
                        .HasColumnType("int");

                    b.Property<int>("Piso_Boca")
                        .HasColumnType("int");

                    b.ToTable("Estomatologico");
                });

            modelBuilder.Entity("OdontologiaWeb.Models.Genero", b =>
                {
                    b.Property<int>("Id_Genero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Genero"));

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Genero");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("OdontologiaWeb.Models.TipoDocumento", b =>
                {
                    b.Property<int>("Id_Documento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Documento"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Documento");

                    b.ToTable("TipoDocumento");
                });

            modelBuilder.Entity("OdontologiaWeb.Models.Usuario", b =>
                {
                    b.Property<string>("Id_Usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aseguradora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Estado_Civil")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Nacido")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Ciudad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Departamento")
                        .HasColumnType("int");

                    b.Property<int>("Id_Documento")
                        .HasColumnType("int");

                    b.Property<int>("Id_Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Acudiente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oficina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
